sudo: required
services:
  - docker

before_install:
  - docker build -t jacm80/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jacm80/react-test npm test

after_succes:
  - docker build -t jacm80/multi-client ./client
  - docker build -t jacm80/multi-nginx ./nginx
  - docker build -t jacm80/multi-server ./server
  - docker build -t jacm80/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jacm80/multi-client
  - docker push jacm80/multi-nginx
  - docker push jacm80/multi-server
  - docker push jacm80/multi-worker